#######################################################
#  _    _ __  __  _____ _           _     _           #
# | |  | |  \/  |/ ____| |         | |   | |          #
# | |__| | \  / | |    | |     ___ | |__ | |__  _   _ #
# |  __  | |\/| | |    | |    / _ \| '_ \| '_ \| | | |#
# | |  | | |  | | |____| |____ (_) | |_) | |_) | |_| |#
# |_|  |_|_|  |_|\_____|______\___/|_.__/|_.__/ \__, |#
#                                                __/ |#
#                                               |___/ #
#######################################################

# Do not change version #. This is for internal use.
version: 1.0-SNAPSHOT


# Play a sound on wheat break.
play-wheat-break-sound: true

first-join-motd: "&6Welcome, %player_name%!"

join-motd: "&7Welcome, %player_name%!"