name: HMCLobby
version: ${project.version}
main: me.raindropz.mc.hmclobby.HMCLobby
api-version: 1.16
authors: [ Raindropz ]
softdepend: [ PlaceholderAPI ]
description: Lobby plugin for HibiscusMC
website: https://hibiscusmc.com
